export const umkmData = [
  {
    id: "1",
    name: "Seblak Mamah Muda",
    category: "Pedas",
    halal: true,
    price: "Rp 15.000",
    rating: 4.8,
    distance: "120m",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1645696288939-e59ed5e3cfa2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGljeSUyMGFzaWFuJTIwbm9vZGxlJTIwc291cCUyMHNlYmxha3xlbnwxfHx8fDE3NzgzMDMwNzh8MA&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: ["GoFood", "GrabFood"],
    payment: ["QRIS", "Cash"],
    description: "Seblak paling viral di area ITB! Kuah kental dengan level kepedasan dari 1-10. Isian melimpah mulai dari kerupuk, makaroni, ceker, hingga tulang ayam.",
    favoriteMenu: ["Seblak Tulang Mercon", "Seblak Ceker Komplit", "Es Teh Manis Jumbo"],
    lat: -6.8906,
    lng: 107.6098,
    openTime: "16:00 - 23:00"
  },
  {
    id: "2",
    name: "Sosis Bakar Bima",
    category: "Gurih",
    halal: true,
    price: "Rp 12.000",
    rating: 4.6,
    distance: "50m",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1774094135152-863707671f5b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxncmlsbGVkJTIwc2F1c2FnZSUyMHNrZXdlciUyMHN0cmVldCUyMGZvb2R8ZW58MXx8fHwxNzc4MzAzMDc4fDA&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: ["ShopeeFood", "GrabFood"],
    payment: ["QRIS", "Cash"],
    description: "Sosis bakar jumbo dengan bumbu BBQ rahasia yang meresap sampai ke dalam. Tersedia berbagai ukuran dan pilihan saus.",
    favoriteMenu: ["Sosis Jumbo Blackpepper", "Otak-otak Bakar Pedas"],
    lat: -6.8910,
    lng: 107.6100,
    openTime: "17:00 - 00:00"
  },
  {
    id: "3",
    name: "Mie Pedas Gila",
    category: "Pedas",
    halal: true,
    price: "Rp 18.000",
    rating: 4.9,
    distance: "200m",
    isOpen: false,
    image: "https://images.unsplash.com/photo-1774668770914-2a37b84c3ef9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGljeSUyMGZyaWVkJTIwbm9vZGxlcyUyMGFzaWFufGVufDF8fHx8MTc3ODMwMzA3OXww&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: ["GoFood"],
    payment: ["QRIS", "Cash", "OVO"],
    description: "Mie goreng pedas dengan taburan ayam cincang dan pangsit goreng renyah. Siap-siap berkeringat!",
    favoriteMenu: ["Mie Iblis Level 5", "Dimsum Siomay", "Es Genderuwo"],
    lat: -6.8915,
    lng: 107.6105,
    openTime: "15:00 - 22:00"
  },
  {
    id: "4",
    name: "Cilok Kuah Kang Asep",
    category: "Gurih",
    halal: true,
    price: "Rp 10.000",
    rating: 4.7,
    distance: "80m",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1654876203651-64761cbcc5cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWF0YmFsbHMlMjBza2V3ZXIlMjBjaWxva3xlbnwxfHx8fDE3NzgzMDMwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: ["GoFood", "GrabFood", "ShopeeFood"],
    payment: ["Cash"],
    description: "Cilok empuk isi daging sapi dengan kuah kaldu gurih pedas. Nikmat disantap malam hari saat udara Bandung mulai dingin.",
    favoriteMenu: ["Cilok Kuah Mercon", "Cilok Bumbu Kacang"],
    lat: -6.8912,
    lng: 107.6095,
    openTime: "16:30 - 23:30"
  },
  {
    id: "5",
    name: "Es Teh Solo Jumbo",
    category: "Manis",
    halal: true,
    price: "Rp 5.000",
    rating: 4.9,
    distance: "10m",
    isOpen: true,
    image: "https://images.unsplash.com/photo-1769737184213-af66b3637edb?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXJnZSUyMGljZWQlMjB0ZWElMjBjdXAlMjBkcmlua3xlbnwxfHx8fDE3NzgzMDMwNzl8MA&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: [],
    payment: ["QRIS", "Cash"],
    description: "Pelepas dahaga andalan mahasiswa ITB. Teh asli Solo yang wangi dan pekat, disajikan dalam gelas jumbo super dingin.",
    favoriteMenu: ["Es Teh Kampul", "Es Teh Tarik", "Es Jeruk Peras"],
    lat: -6.8908,
    lng: 107.6102,
    openTime: "10:00 - 22:00"
  },
  {
    id: "6",
    name: "Martabak Manis Ganesha",
    category: "Manis",
    halal: true,
    price: "Rp 35.000",
    rating: 4.8,
    distance: "250m",
    isOpen: false,
    image: "https://images.unsplash.com/photo-1776073976406-034912561892?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxpbmRvbmVzaWFuJTIwbWFydGFiYWslMjBzd2VldHxlbnwxfHx8fDE3NzgzMDMwODV8MA&ixlib=rb-4.1.0&q=80&w=1080",
    delivery: ["GoFood", "GrabFood"],
    payment: ["QRIS", "Cash"],
    description: "Martabak tebal dengan butter melimpah. Tekstur sarang lebah yang sempurna dan isian yang ga pelit.",
    favoriteMenu: ["Martabak Coklat Keju Wijen", "Martabak Jagung Keju"],
    lat: -6.8920,
    lng: 107.6110,
    openTime: "17:00 - 00:00"
  }
];
